baseURL: 'https://engineering-projects-society.github.io/website/'
languageCode: en-us
title: EPS
theme: ananke
resourceDir: ''

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 10
googleAnalytics: ''
enableRobotsTXT: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

params:
  date_format: '2006'
  text_color: ''
  author: ''
  favicon: ''
  site_logo: 'images/icons/eps_logo_shorttext_allbake.svg'
  description: The last theme you'll ever need. Maybe.
  background_color_class: bg-black
  recent_posts_number: 12
  ananke_socials:
    - name: github
      url: 'https://github.com/Engineering-Projects-Society'
    - name: discord
      url: 'https://discord.gg/86eGFsVMJU'
      color: '#5865F2'
      label: ''
    - name: twitter
      url: 'https://twitter.com/ncl_eps'
    - name: linkedin
      url: 'https://linkedin.com/company/nclenginesoc'
    - name: facebook
      url: 'https://www.facebook.com/nclenginesoc'
    - name: instagram
      url: 'https://www.instagram.com/ncl_eps'
  mainSections: [post, projects, members]
  defaultImage: images/newcastle-gfe3a4765f_1920.jpg
