baseURL: 'https://engineering-projects-society.github.io/'
languageCode: en-us
title: EPS
theme: ananke
resourceDir: ''

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 10
googleAnalytics: ''
enableRobotsTXT: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

params:
  date_format: '2006'
  text_color: ''
  author: ''
  favicon: ''
  site_logo: ''
  description: The last theme you'll ever need. Maybe.
  background_color_class: bg-black
  recent_posts_number: 12
  ananke_socials:
    - name: github
      url: 'https://github.com/Engineering-Projects-Society'
    - name: discord
      url: 'https://discord.gg/86eGFsVMJU'
      color: '#5865F2'
      label: ''
  mainSections: [post, projects, members]
  defaultImage: images/newcastle-gfe3a4765f_1920.jpg
